apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-dev
  namespace: vegan
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api-service-dev
  template:
    metadata:
      labels:
        app: api-service-dev
    spec:
      containers:
        - name: api-service-dev
          image: harbor.kyojs.com/vegan/api-server-dev:develop
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 3200
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 3200
            initialDelaySeconds: 60
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 3200
            failureThreshold: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          ports:
            - containerPort: 3200
          envFrom:
            - secretRef:
                name: api-server-dev

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-service-dev
  namespace: vegan
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 65
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service-dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-db
  namespace: vegan
spec:
  type: ExternalName
  externalName: kyojs.synology.me
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-dev-lb
  namespace: vegan
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: api-service-dev
  ports:
    - name: api-server-dev
      protocol: TCP
      port: 3201
      targetPort: 3200
